version: '3'

services:
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    container_name: blog_django
    depends_on:
      - postgres
    volumes:
      - .:/src:z
    env_file:
      - ./.env
    environment:
      - MODE=prod
      - USE_DOCKER=True
      - DJANGO_DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    expose:
      - "8000"
    command: /start

  postgres:
    image: postgres:alpine
    container_name: blog_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data:Z
    env_file:
      - ./.env
    expose:
      - "5432"

  nginx:
    image: nginx:alpine
    container_name: blog_nginx
    volumes:
      - ./apps/media:/media:ro
      - ./compose/nginx/:/etc/nginx/conf.d/
    ports:
      - "80:80"
    depends_on:
      - django

volumes:
  postgres_data:
